# Generated by Django 4.1 on 2022-08-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student_phone_student_social_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='social_profile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
