# Generated by Django 4.1 on 2022-08-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_program_image_teacher_programs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='motivation_images', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Мотивация',
                'verbose_name_plural': 'Мотивации',
            },
        ),
        migrations.AlterField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='programs_images', verbose_name='Изображение'),
        ),
    ]
