# Generated by Django 4.1 on 2022-08-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_motivation_alter_program_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
    ]
