# Generated by Django 4.1 on 2022-08-18 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_course_slug_alter_program_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='programs_images', verbose_name='Изображение')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='home.program', verbose_name='Галерея')),
            ],
        ),
    ]
