# Generated by Django 4.1 on 2022-08-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_programgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='detail_description',
            field=models.TextField(blank=True, null=True, verbose_name='Детальное описание'),
        ),
    ]
