# Generated by Django 4.1 on 2022-08-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_program_detail_description_program_detail_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='detail_3',
            field=models.TextField(blank=True, null=True, verbose_name='Блок 3'),
        ),
        migrations.AddField(
            model_name='program',
            name='detail_4',
            field=models.TextField(blank=True, null=True, verbose_name='Блок 4'),
        ),
        migrations.AlterField(
            model_name='program',
            name='detail_1',
            field=models.TextField(blank=True, null=True, verbose_name='Блок 1'),
        ),
        migrations.AlterField(
            model_name='program',
            name='detail_2',
            field=models.TextField(blank=True, null=True, verbose_name='Блок 2'),
        ),
    ]
