# Generated by Django 4.1 on 2022-08-18 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_program_detail_3_program_detail_4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='detail_1',
        ),
        migrations.RemoveField(
            model_name='program',
            name='detail_2',
        ),
        migrations.RemoveField(
            model_name='program',
            name='detail_3',
        ),
        migrations.RemoveField(
            model_name='program',
            name='detail_4',
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(verbose_name='Краткое описание'),
        ),
        migrations.CreateModel(
            name='ProgramDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Детальное описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='program_detail_images', verbose_name='Изображение')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='home.program', verbose_name='Блоки')),
            ],
        ),
    ]
