# Generated by Django 4.1 on 2022-08-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_program_detail_1_remove_program_detail_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programdetail',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Заголовок'),
        ),
    ]
