# Generated by Django 4.1 on 2022-08-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_programdetail_image_alter_programgallery_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider_images', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Главный слайдер',
                'verbose_name_plural': 'Главный слайдер',
            },
        ),
    ]
