# Generated by Django 4.1 on 2022-08-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_slider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'изображение', 'verbose_name_plural': 'Главный слайдер'},
        ),
        migrations.AddField(
            model_name='slider',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
