# Generated by Django 4.1 on 2022-08-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_slider_options_slider_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['course_date'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'изображение', 'verbose_name_plural': 'Главная страница'},
        ),
        migrations.AddField(
            model_name='slider',
            name='image_latest_coures_inner',
            field=models.ImageField(blank=True, null=True, upload_to='slider_images', verbose_name='Изображение_блока'),
        ),
    ]
